### ISSUE TITLE
Don't lock the app immediately after leaving it. Introduce a time delay.

### ISSUE THREAD

**Issue by tficharmers** [mymonero/mymonero-app-ios#63] opened 2018-05-17 20:47 UTC
Use case: I was sending some bitcoin to the Shapeshift app and so needed to get my receiving MyMonero address. I went backwards and forwards between apps several times, just checking the addresses a few times because of my OCD. Each time I left the MyMonero app, I would have to re-enter my password to get back in. It was a bit of a drag. I'd only left the app for a few seconds.

With my bitcoin wallet/password app/fiat banking apps, they give you a short period of time (10-20 seconds) to leave the app and return before they lock you out and require you to log back in. I wonder whether this should be considered for MyMonero?

**Comment by paulshapiro** [comment] 2018-05-17 20:51
I've definitely considered this but the problem is that the system multitasker screenshotter will screenshot the app when you leave, meaning it may reveal secrets such as mnemonic, and the system won't give the app any processing time while it's in the background so we also can't quite lock it after a delay - only after coming back after a delay, by which point secrets may be revealed as well..

**Comment by paulshapiro** [comment] 2018-05-18 22:38
Open to suggestions but closing this for now

**Closed** 2018-05-18 22:38 UTC
